spring:
    application:
        name: bridge
    r2dbc:
        url: r2dbc:mysql://localhost:23306/bridge?ssl=false
        username: bridge
        password: bridge!@#$1234
    flyway:
        enabled: false